spring.application.name=dan-financial-book

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/dan-financial-book
spring.datasource.username=dan
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true